Logan change backround visibility
ucsb-cs156-f22/f22-5pm-happycows pull request #36
Opened 2022-11-27 02:33 UTC by Geivet

In this pull request, the leaderboard page was changed in order to see any number shown in the leaderboard. This was done by changing the opacity so that even if the numbers were listed on the barn in the background image, they would still be legible.

2022-11-27 20:51 UTC, briggsrr requested changes
# Issues 
There are a few things to look at before merging: 
1. The leaderboard is still hard to see
2. Opacity change is applied to the entire page (the div, its contents and all its children, and I believe this cannot be changed just by overriding the opacity in child elements.)

# Explanation of issues 
Here is the staff example leaderboard page:
<img width="1037" alt="Screen Shot 2022-11-27 at 12 20 44 PM" src="https://user-images.githubusercontent.com/53193453/204158248-2fa0d2c0-2162-437b-aa2d-67754be30ecd.png">


Here is this branch's leaderboard page: 

<img width="1063" alt="Screen Shot 2022-11-27 at 12 20 34 PM" src="https://user-images.githubusercontent.com/53193453/204158252-1757996f-c37e-40a2-a6c0-cae4c661013d.png">
You can see the entire page is affected by the opacity change and the leaderboard table is still hard to see. 

# Potential solutions 
1. (easier) I know the issue says to [change background visibility so that text in Leaderboard table is legible](https://github.com/ucsb-cs156-f22/f22-5pm-happycows/issues/28) , but perhaps instead you could _`change table visibility`_ so that the text in Leaderboard table is legible. This could mean adding an inline style like background color or text shadows to the "leaderboard table" component or parent "our table" (for all tables). 
2. (harder) You can use rgba ([more info on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgba())) value for a transparent background color + don't forget to give a negative z-index value to the image so it stacks behind the content. Source :  [this stack overflow post](https://stackoverflow.com/questions/24853342/css-background-transparency-with-text-fully-visible)

2022-11-28 03:01 UTC, pconrad commented
Agreed with @briggsrr 

Here's another way to do it: 

https://github.com/ucsb-cs156-f22/f22-7pm-happycows/pull/33/files

it's fine to copy their approach as long as you give them credit in the PR description.

2022-11-29 02:28 UTC, pconrad commented
To address the mutation coverage gap in Footer.js:

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1119017/204423773-023b51aa-3afc-4720-8f4a-53414a4d787d.png">

You can use the approach in this PR:

https://github.com/ucsb-cs156-f22/f22-6pm-happycows/pull/51

2022-11-29 02:30 UTC, pconrad commented
For JobComingSoon.js, I think the right thing to do is just delete the file.. I don't think we are using it anywhere anymore

<img width="715" alt="image" src="https://user-images.githubusercontent.com/1119017/204424063-216aa590-9efe-40c9-9dce-f95d35cb858c.png">

2022-11-29 02:32 UTC, pconrad requested changes
code LGTM.. but see my comments about how to fix the test failures.

2022-11-30 00:46 UTC, briggsrr approved these changes
LGTM - Tested on heroku. Looks good!

2022-11-30 06:03 UTC, pconrad approved these changes
LGTM

2022-11-30 06:04 UTC, merged