cw - added cowHealth field to UserCommons.java
ucsb-cs156-f22/f22-5pm-happycows pull request #49
Opened 2022-11-29 03:45 UTC by cyril-wang

In this PR, we added in the cowHealth field into `UserCommons.java` that keeps track of the average cow health in a user's common. In addition, we also implemented changes into the `UserCommonsController.java` that updated the average cow health when cows were bought or sold. 

To test, I recommend running `mvn test` first, then either running it locally on localhost or through the heroku-qa. While doing so, check that the cowHealth field shows up in the Play Page under `Your Farm Stats`. For example, like these screenshots. 
![image](https://user-images.githubusercontent.com/78510771/204433141-f0be1069-929c-493b-9a83-7e3e3a4ce488.png)
![image](https://user-images.githubusercontent.com/78510771/204433034-d7251a04-22eb-4232-8fd9-9b04b2a0c102.png)

If you run into errors, such as errors with communicating with the backend or sql unable to perform query, when trying to join a common or when accessing the play page and leaderboard page, then try running `mvn clean` if on localhost or resetting the database if on heroku.

2022-11-30 01:08 UTC, Geivet approved these changes
LGTM!

2022-11-30 01:38 UTC, nick-pellegrin submitted a review, later dismissed
Looks good!

2022-11-30 06:12 UTC, pconrad requested changes
There a few small changes I'd like to request based on an updated understanding of how cow health will work.

Otherwise, looks good to me.

2022-11-30 06:12 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
> +        .cowHealth(0)
Can we set the initial cow health to 100 instead?

2022-11-30 06:12 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
> +          userCommons.setCowHealth((userCommons.getCowHealth()*userCommons.getNumOfCows() + 100) / (userCommons.getNumOfCows() + 1));
No... we don't want to do this.  Instead, there is a job that will update cow health periodically.

There may be some old documentation that suggests this is the way to do it, but that's no longer how we are doing it.   Please leave cow health unchanged when we buy/sell cows.

2022-11-30 06:12 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
> +          if (userCommons.getNumOfCows() == 0) {
No... please leave the cow health unchanged when buying and selling cows.

2022-12-01 01:58 UTC, pconrad approved these changes
LGTM!

2022-12-01 01:59 UTC, merged